// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Entry struct {
	ID         string
	Title      string
	Ciphertext []byte
	ModifiedAt int64
	Deleted    int64
}

type VaultMetum struct {
	ID           int64
	Version      int64
	KdfSalt      []byte
	KdfTime      int64
	KdfMemory    int64
	KdfThreads   int64
	KdfKeyLen    int64
	EncryptedDek []byte
	Verifier     []byte
}
