// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const entryExists = `-- name: EntryExists :one
SELECT
  EXISTS (
    SELECT 1
    FROM entries
    WHERE id = ? AND deleted = 0
  )
`

func (q *Queries) EntryExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, entryExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getEntry = `-- name: GetEntry :one
SELECT id, title, ciphertext, modified_at, deleted FROM entries WHERE id = ? AND deleted = 0
`

func (q *Queries) GetEntry(ctx context.Context, id string) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Ciphertext,
		&i.ModifiedAt,
		&i.Deleted,
	)
	return i, err
}

const getMeta = `-- name: GetMeta :one
SELECT id, version, kdf_salt, kdf_time, kdf_memory, kdf_threads, kdf_key_len, encrypted_dek, verifier FROM vault_meta WHERE id = 1
`

func (q *Queries) GetMeta(ctx context.Context) (VaultMetum, error) {
	row := q.db.QueryRowContext(ctx, getMeta)
	var i VaultMetum
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.KdfSalt,
		&i.KdfTime,
		&i.KdfMemory,
		&i.KdfThreads,
		&i.KdfKeyLen,
		&i.EncryptedDek,
		&i.Verifier,
	)
	return i, err
}

const initMeta = `-- name: InitMeta :exec
INSERT INTO vault_meta (
  id,
  version,
  kdf_salt,
  kdf_time,
  kdf_memory,
  kdf_threads,
  kdf_key_len,
  encrypted_dek,
  verifier
)
VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InitMetaParams struct {
	Version      int64
	KdfSalt      []byte
	KdfTime      int64
	KdfMemory    int64
	KdfThreads   int64
	KdfKeyLen    int64
	EncryptedDek []byte
	Verifier     []byte
}

func (q *Queries) InitMeta(ctx context.Context, arg InitMetaParams) error {
	_, err := q.db.ExecContext(ctx, initMeta,
		arg.Version,
		arg.KdfSalt,
		arg.KdfTime,
		arg.KdfMemory,
		arg.KdfThreads,
		arg.KdfKeyLen,
		arg.EncryptedDek,
		arg.Verifier,
	)
	return err
}

const insertEntry = `-- name: InsertEntry :exec
INSERT INTO entries (
  id,
  title,
  ciphertext,
  modified_at,
  deleted
)
VALUES (?, ?, ?, ?, 0)
`

type InsertEntryParams struct {
	ID         string
	Title      string
	Ciphertext []byte
	ModifiedAt int64
}

func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertEntry,
		arg.ID,
		arg.Title,
		arg.Ciphertext,
		arg.ModifiedAt,
	)
	return err
}

const listEntries = `-- name: ListEntries :many
SELECT id, title, modified_at FROM entries WHERE deleted = 0
`

type ListEntriesRow struct {
	ID         string
	Title      string
	ModifiedAt int64
}

func (q *Queries) ListEntries(ctx context.Context) ([]ListEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesRow
	for rows.Next() {
		var i ListEntriesRow
		if err := rows.Scan(&i.ID, &i.Title, &i.ModifiedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeleted = `-- name: SetDeleted :exec
UPDATE entries
SET deleted = 1
WHERE id = ? AND deleted = 0
`

func (q *Queries) SetDeleted(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setDeleted, id)
	return err
}

const updateEntry = `-- name: UpdateEntry :exec
UPDATE entries
SET title = ?, ciphertext = ?, modified_at = ?
WHERE id = ? AND deleted = 0
`

type UpdateEntryParams struct {
	Title      string
	Ciphertext []byte
	ModifiedAt int64
	ID         string
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) error {
	_, err := q.db.ExecContext(ctx, updateEntry,
		arg.Title,
		arg.Ciphertext,
		arg.ModifiedAt,
		arg.ID,
	)
	return err
}
